version: '3'
services:
  web:
    build: .
    image: test:latest
    volumes:
      - ./BakeryManagementSystem:/BakeryManagementSystem/
    entrypoint:
      - /bin/bash
      - -c
      - python3 manage.py runserver --insecure 0.0.0.0:8000

    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=password
    networks:
      my-network:
        ipv4_address: 181.18.0.3
    ports:
      - "8000:8000"

    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      my-network:
        ipv4_address: 181.18.0.2

volumes:
    postgres_data:
      external: True

networks:
  my-network:
    external: True
